# Generated by Django 3.2.4 on 2022-05-15 01:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo_producto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id de tipo producto')),
                ('nombreTipo', models.CharField(max_length=50, verbose_name='Nombre del producto')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id producto')),
                ('nombreProducto', models.CharField(max_length=200, verbose_name='Nombre del producto')),
                ('descripcion', models.CharField(max_length=200, verbose_name='Descripcion del producto')),
                ('precio', models.IntegerField(verbose_name='Precio del producto')),
                ('tipo_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipoproducto')),
            ],
        ),
    ]
