# Generated by Django 3.2.4 on 2022-05-15 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='idProducto',
            new_name='id_producto',
        ),
    ]
