# Generated by Django 3.2.4 on 2022-05-15 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_idproducto_producto_id_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='disponibilidad',
            field=models.IntegerField(default=1, verbose_name='Disponibilidad'),
            preserve_default=False,
        ),
    ]
